# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def __init__(self):
        self.aux = 0
        self.texto = []
        self.n = []

    def add(self,x):
        if x.isnumeric() != 1:
            n1 = int("".join(self.n))
            self.texto.append(n1)
            self.texto.append(x)
            if x == '=':
                self.calc()
            self.n = []
        else:
            self.n.append(x)
            self.numeros.setText(f"{''.join(self.n)}")


    def calc(self):
        if self.texto[1]=="+":
            self.aux = int(self.texto[0] + self.texto[2])
        if self.texto[1]=="-":
            self.aux = int(self.texto[0] - self.texto[2])
        if self.texto[1]=="X":
            self.aux = int(self.texto[0] * self.texto[2])
        if self.texto[1]=="/":
            self.aux = round(float(self.texto[0] / self.texto[2]),5)
        self.texto= []
        print(self.aux)
        self.numeros.setText(str(self.aux))





    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(238, 308)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icone/2927547.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cima = QtWidgets.QFrame(self.centralwidget)
        self.cima.setStyleSheet("background-color:rgb(237, 252, 255);\n"
"\n"
"")
        self.cima.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cima.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cima.setObjectName("cima")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cima)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.cima)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setStyleSheet("QFrame{\n"
"background-color:\'white\';\n"
"border-radius:10;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.numeros = QtWidgets.QLabel(self.frame)
        self.numeros.setGeometry(QtCore.QRect(10, 0, 201, 31))
        self.numeros.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.numeros.setStyleSheet("font: 25 16pt \"Microsoft YaHei\";")
        self.numeros.setTextFormat(QtCore.Qt.AutoText)
        self.numeros.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numeros.setObjectName("numeros")
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.cima)
        self.widget.setStyleSheet("QPushButton{\n"
"border:2px solid black;\n"
"background-color:\'white\';\n"
"border-radius:10;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(226, 226, 226);\n"
"\n"
"}\n"
"\n"
"QPushButton#botaoMais{\n"
"background-color:rgb(185, 255, 213);\n"
"}\n"
"\n"
"QPushButton#botaoMais:hover{\n"
"background-color:rgb(130, 171, 144)\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.botao2 = QtWidgets.QPushButton(self.widget)
        self.botao2.setMinimumSize(QtCore.QSize(50, 50))
        self.botao2.setMaximumSize(QtCore.QSize(50, 50))
        self.botao2.setObjectName("botao2")
        self.gridLayout.addWidget(self.botao2, 3, 3, 1, 1)
        self.botao8 = QtWidgets.QPushButton(self.widget)
        self.botao8.setMinimumSize(QtCore.QSize(50, 50))
        self.botao8.setMaximumSize(QtCore.QSize(50, 50))
        self.botao8.setObjectName("botao8")
        self.gridLayout.addWidget(self.botao8, 0, 3, 1, 1)
        self.botaoDiv = QtWidgets.QPushButton(self.widget)
        self.botaoDiv.setMinimumSize(QtCore.QSize(50, 50))
        self.botaoDiv.setMaximumSize(QtCore.QSize(50, 50))
        self.botaoDiv.setObjectName("botaoDiv")
        self.gridLayout.addWidget(self.botaoDiv, 0, 7, 1, 1)
        self.botao5 = QtWidgets.QPushButton(self.widget)
        self.botao5.setMinimumSize(QtCore.QSize(50, 50))
        self.botao5.setMaximumSize(QtCore.QSize(50, 50))
        self.botao5.setObjectName("botao5")
        self.gridLayout.addWidget(self.botao5, 2, 3, 1, 1)
        self.botao6 = QtWidgets.QPushButton(self.widget)
        self.botao6.setMinimumSize(QtCore.QSize(50, 50))
        self.botao6.setMaximumSize(QtCore.QSize(50, 50))
        self.botao6.setObjectName("botao6")
        self.gridLayout.addWidget(self.botao6, 2, 5, 1, 1)
        self.botao4 = QtWidgets.QPushButton(self.widget)
        self.botao4.setMinimumSize(QtCore.QSize(50, 50))
        self.botao4.setMaximumSize(QtCore.QSize(50, 50))
        self.botao4.setObjectName("botao4")
        self.gridLayout.addWidget(self.botao4, 2, 0, 1, 1)
        self.botao1 = QtWidgets.QPushButton(self.widget)
        self.botao1.setMinimumSize(QtCore.QSize(50, 50))
        self.botao1.setMaximumSize(QtCore.QSize(50, 50))
        self.botao1.setObjectName("botao1")
        self.gridLayout.addWidget(self.botao1, 3, 0, 1, 1)
        self.botao3 = QtWidgets.QPushButton(self.widget)
        self.botao3.setMinimumSize(QtCore.QSize(50, 50))
        self.botao3.setMaximumSize(QtCore.QSize(50, 50))
        self.botao3.setObjectName("botao3")
        self.gridLayout.addWidget(self.botao3, 3, 5, 1, 1)
        self.botaoVezes = QtWidgets.QPushButton(self.widget)
        self.botaoVezes.setMinimumSize(QtCore.QSize(50, 50))
        self.botaoVezes.setMaximumSize(QtCore.QSize(50, 50))
        self.botaoVezes.setObjectName("botaoVezes")
        self.gridLayout.addWidget(self.botaoVezes, 2, 7, 1, 1)
        self.botao00 = QtWidgets.QPushButton(self.widget)
        self.botao00.setMinimumSize(QtCore.QSize(50, 50))
        self.botao00.setMaximumSize(QtCore.QSize(50, 50))
        self.botao00.setObjectName("botao00")
        self.gridLayout.addWidget(self.botao00, 4, 3, 1, 1)
        self.botaoMenos = QtWidgets.QPushButton(self.widget)
        self.botaoMenos.setMinimumSize(QtCore.QSize(50, 50))
        self.botaoMenos.setMaximumSize(QtCore.QSize(50, 50))
        self.botaoMenos.setObjectName("botaoMenos")
        self.gridLayout.addWidget(self.botaoMenos, 3, 7, 1, 1)
        self.botao0 = QtWidgets.QPushButton(self.widget)
        self.botao0.setMinimumSize(QtCore.QSize(50, 50))
        self.botao0.setMaximumSize(QtCore.QSize(50, 50))
        self.botao0.setObjectName("botao0")
        self.gridLayout.addWidget(self.botao0, 4, 0, 1, 1)
        self.botao7 = QtWidgets.QPushButton(self.widget)
        self.botao7.setMinimumSize(QtCore.QSize(50, 50))
        self.botao7.setMaximumSize(QtCore.QSize(50, 50))
        self.botao7.setObjectName("botao7")
        self.gridLayout.addWidget(self.botao7, 0, 0, 1, 1)
        self.botao9 = QtWidgets.QPushButton(self.widget)
        self.botao9.setMinimumSize(QtCore.QSize(50, 50))
        self.botao9.setMaximumSize(QtCore.QSize(50, 50))
        self.botao9.setObjectName("botao9")
        self.gridLayout.addWidget(self.botao9, 0, 5, 1, 1)
        self.botaoMais = QtWidgets.QPushButton(self.widget)
        self.botaoMais.setMinimumSize(QtCore.QSize(50, 50))
        self.botaoMais.setMaximumSize(QtCore.QSize(50, 50))
        self.botaoMais.setObjectName("botaoMais")
        self.gridLayout.addWidget(self.botaoMais, 4, 5, 1, 1)
        self.botaoIgual = QtWidgets.QPushButton(self.widget)
        self.botaoIgual.setMinimumSize(QtCore.QSize(50, 50))
        self.botaoIgual.setMaximumSize(QtCore.QSize(50, 50))
        self.botaoIgual.setObjectName("botaoIgual")
        self.gridLayout.addWidget(self.botaoIgual, 4, 7, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout.addWidget(self.cima)
        self.baixo = QtWidgets.QFrame(self.centralwidget)
        self.baixo.setMinimumSize(QtCore.QSize(0, 20))
        self.baixo.setMaximumSize(QtCore.QSize(16777215, 30))
        self.baixo.setStyleSheet("QFrame{\n"
"background-color:rgb(244, 255, 254)\n"
"}\n"
"\n"
"QLabel{\n"
"text-align:right\n"
"}")
        self.baixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.baixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.baixo.setObjectName("baixo")
        self.nome = QtWidgets.QLabel(self.baixo)
        self.nome.setGeometry(QtCore.QRect(0, 0, 60, 16))
        self.nome.setObjectName("nome")
        self.verticalLayout.addWidget(self.baixo)
        MainWindow.setCentralWidget(self.centralwidget)

        self.botao0.clicked.connect(lambda: self.add('0'))
        self.botao1.clicked.connect(lambda: self.add('1'))
        self.botao2.clicked.connect(lambda: self.add('2'))
        self.botao3.clicked.connect(lambda: self.add('3'))
        self.botao4.clicked.connect(lambda: self.add('4'))
        self.botao5.clicked.connect(lambda: self.add('5'))
        self.botao6.clicked.connect(lambda: self.add('6'))
        self.botao7.clicked.connect(lambda: self.add('7'))
        self.botao8.clicked.connect(lambda: self.add('8'))
        self.botao9.clicked.connect(lambda: self.add('9'))
        self.botaoDiv.clicked.connect(lambda: self.add('/'))
        self.botaoMais.clicked.connect(lambda: self.add('+'))
        self.botaoMenos.clicked.connect(lambda: self.add('-'))
        self.botaoVezes.clicked.connect(lambda: self.add('X'))
        self.botao00.clicked.connect(lambda: self.add('00'))
        self.botaoIgual.clicked.connect(lambda: self.add('='))


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.numeros.setText(_translate("MainWindow", "0"))
        self.botao2.setText(_translate("MainWindow", "2"))
        self.botao8.setText(_translate("MainWindow", "8"))
        self.botaoDiv.setText(_translate("MainWindow", "÷"))
        self.botao5.setText(_translate("MainWindow", "5"))
        self.botao6.setText(_translate("MainWindow", "6"))
        self.botao4.setText(_translate("MainWindow", "4"))
        self.botao1.setText(_translate("MainWindow", "1"))
        self.botao3.setText(_translate("MainWindow", "3"))
        self.botaoVezes.setText(_translate("MainWindow", "X"))
        self.botao00.setText(_translate("MainWindow", "00"))
        self.botaoMenos.setText(_translate("MainWindow", "-"))
        self.botao0.setText(_translate("MainWindow", "0"))
        self.botao7.setText(_translate("MainWindow", "7"))
        self.botao9.setText(_translate("MainWindow", "9"))
        self.botaoMais.setText(_translate("MainWindow", "+"))
        self.botaoIgual.setText(_translate("MainWindow", "="))
        self.nome.setText(_translate("MainWindow", "@ViniciUwUs"))
import file


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
